version: 1.0.{build}
configuration: Release
platform: Any CPU

before_build:
- nuget restore src\Mixpanel.NET\Mixpanel.NET.sln

build:
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
  
test: off

nuget:
  account_feed: true
  project_feed: true
