version: 1.0.{build}
configuration: Release
platform: Any CPU

before_build:
- nuget restore

nuget:
  account_feed: true
  project_feed: true

build:
  publish_nuget: true
  verbosity: minimal
  
test: off


